### ISSUE TITLE
Update PDCurses to 407d9c2 or newer

### ISSUE THREAD

**Issue by vyv03354** [zephyrproject-rtos/windows-curses#1]
I want the fix of wmcbrine/PDCurses#53.

**Comment by ulfalizer** [comment]
On it. Ran into a snag while updating the wheels (https://github.com/wmcbrine/PDCurses/issues/55), but maybe I could hack around it manually if needed.

**Comment by ulfalizer** [comment]
Done.

Tell me if you run into any issues.
