### ISSUE TITLE
insnstr prints garbage text with big n

### ISSUE THREAD

**Issue by dhnam** [zephyrproject-rtos/windows-curses#2]
tried
```python
stdscr.insnstr(0, 0, "test", 10)
```
gave me

![test^@^@^@^@^@^@](https://i.imgur.com/7gPRNuO.png)
----------
While I expected something like shown in [this stackoverflow result](https://stackoverflow.com/questions/35422886/is-curses-window-insnstr-broken-in-python-3-for-wide-characters)

code
```python
window.insnstr(0, 0, "insnstr", 80)
```

result
 ![normal](https://i.stack.imgur.com/9s1Xa.png)

**Comment by ulfalizer** [comment]
Think I traced it down to a PDCurses issue: https://github.com/wmcbrine/PDCurses/issues/72

**Comment by ulfalizer** [comment]
Fixed by updating PDCurses to get https://github.com/wmcbrine/PDCurses/commit/b12c4a5212e97cf83f0074618c1473253fad4131 in.
