### ISSUE TITLE
 MSYS2 terminal is not supported (?)

### ISSUE THREAD

**Issue by dobairoland** [zephyrproject-rtos/windows-curses#4]
I'm trying to do `pip install --user windows-curses` in MSYS2 terminal as a dependency for https://github.com/ulfalizer/Kconfiglib and receiving the following error:
```
Collecting windows-curses
  ERROR: Could not find a version that satisfies the requirement windows-curses (from versions: none)
ERROR: No matching distribution found for windows-curses
```

The package seems to be required because without it I'm receiving the following error:
```
Traceback (most recent call last):
  File "C:/msys32/home/Roland/esp/esp-idf/tools/kconfig_new/menuconfig.py", line 3280, in <module>
    _main()
  File "C:/msys32/home/Roland/esp/esp-idf/tools/kconfig_new/menuconfig.py", line 647, in _main
    menuconfig(standard_kconfig())
  File "C:/msys32/home/Roland/esp/esp-idf/tools/kconfig_new/menuconfig.py", line 716, in menuconfig
    print(curses.wrapper(_menuconfig))
  File "C:/msys32/mingw32/lib/python3.7\curses\__init__.py", line 81, in wrapper
    stdscr = initscr()
  File "C:/msys32/mingw32/lib/python3.7\curses\__init__.py", line 30, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminfo database

```

Or the curses library is not supported at all in MSYS2?

**Comment by ulfalizer** [comment]
> I'm trying to do `pip install --user windows-curses` in MSYS2 terminal as a dependency for https://github.com/ulfalizer/Kconfiglib and receiving the following error:
> 
> ```
> Collecting windows-curses
>   ERROR: Could not find a version that satisfies the requirement windows-curses (from versions: none)
> ERROR: No matching distribution found for windows-curses
> ```

Haven't tested it with MSYS2. Unless it's using a regular Windows console, it won't be compatible. `pip` is probably trying to find some MSYS-specific version of the binary package, that's not in https://pypi.org/project/windows-curses/#files.

> ```
> Traceback (most recent call last):
>   File "C:/msys32/home/Roland/esp/esp-idf/tools/kconfig_new/menuconfig.py", line 3280, in <module>
>     _main()
>   File "C:/msys32/home/Roland/esp/esp-idf/tools/kconfig_new/menuconfig.py", line 647, in _main
>     menuconfig(standard_kconfig())
>   File "C:/msys32/home/Roland/esp/esp-idf/tools/kconfig_new/menuconfig.py", line 716, in menuconfig
>     print(curses.wrapper(_menuconfig))
>   File "C:/msys32/mingw32/lib/python3.7\curses\__init__.py", line 81, in wrapper
>     stdscr = initscr()
>   File "C:/msys32/mingw32/lib/python3.7\curses\__init__.py", line 30, in initscr
>     fd=_sys.__stdout__.fileno())
> _curses.error: setupterm: could not find terminfo database
> ```

Looks like it gets further than it'd get in native Windows Python without `windows-curses` at least. Could see if terminfo definitions need to be installed separately maybe.

**Comment by dobairoland** [comment]
A little update:
`TERM` variable is defined as `xterm` but `TERMINFO` is not.  The `xterm` file is in directory `/usr/share/terminfo/78`  so I defined `TERMINFO=/usr/share/terminfo/78`. The error message has changed to `_curses.error: setupterm: could not find terminal`. I guess the reason is that there is no `xterm` executable. So far I wasn't able to set it to something which would work.

**Comment by ulfalizer** [comment]
Maybe `ncurses` needs to be installed as a package. See https://github.com/msys2/msys2/wiki/Using-packages.

From looking at https://github.com/msys2/MINGW-packages/issues/5437, there seems to be one called mingw-w64-x86_64-ncurses, for example.

**Comment by dobairoland** [comment]
Yes, I have all of these:
```
local/mingw-w64-i686-ncurses 6.1.20190630-1
local/mingw-w64-i686-pdcurses 4.1.0-3
local/mingw-w64-x86_64-ncurses 6.1.20190630-1
local/mingw-w64-x86_64-pdcurses 4.1.0-3
local/ncurses 6.1.20190615-1 (base)
local/ncurses-devel 6.1.20190615-1 (development)
```

**Comment by ulfalizer** [comment]
I'd try uninstalling all the `pdcurses` stuff and then try again (maybe uninstall/reinstall `ncurses` too). `setupterm()` is part of PDCurses/ncurses at least. It's getting called and fails.

Honestly, I'm just guessing at this point though. Would help to know what kind of terminal MSYS 2 uses. I'm not really a Windows guy, despite this project. ;)

**Comment by dobairoland** [comment]
I can build and run this C code
```c
#include <ncurses/ncurses.h>

int main()
{
    initscr();
    noecho();
    cbreak();
    keypad(stdscr, 1);

    printw("Hello World !!!");
    refresh();
    getch();

    nocbreak();
    keypad(stdscr, 0);
    echo();
    endwin();

    return 0;
}
```

if I set the following environment variables:

```
TERMINFO=/usr/share/terminfo
TERM=xterm
```

I'm trying the same with Python:

```python
import curses

stdscr = curses.initscr()
curses.noecho()
curses.cbreak()
stdscr.keypad(1)


curses.nocbreak()
stdscr.keypad(0)
curses.echo()
curses.endwin()
```
The result is:
```
_curses.error: cbreak() returned ERR
```

So I think Python needs something extra but I cannot figure it what. The error message is not very helpful.

**Comment by dobairoland** [comment]
I tried to hack this project and build something for MSYS but I'm afraid that it is not an easy task. It would require so much changes so I guess there is no meaning to try to do it....
