### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by BigFatBass** [zephyrproject-rtos/windows-curses#45]
Hello, 

Python 3.12 (final) has officially released.
Could you please add support for Python 3.12?

The fact is that I use a nvitop (https://github.com/XuehaiPan/nvitop) app that is actively supporting.
It depends on curses (with libncursesw). So, I cannot install the nvitop in Windows under Python 3.12 on the following error:

`ERROR: Cannot install nvitop==0.10.0, nvitop==0.10.1, nvitop==0.10.2, nvitop==0.11.0, nvitop==0.9.0, nvitop==1.0.0, nvitop==1.1.1, nvitop==1.1.2, nvitop==1.2.0, nvitop==1.3.0 and nvitop==1.3.1 because these package versions have conflicting dependencies.`

`The conflict is caused by:`
    `nvitop 1.3.1 depends on windows-curses>=2.2.0; platform_system == "Windows"`
    `nvitop 1.3.0 depends on windows-curses>=2.2.0; platform_system == "Windows"`
    `etc`

**Comment by maphew** [comment]
In the readme there's a message saying "This project is not actively maintained and is looking for maintainers" so it might be awhile. However the bottom of the readme has pretty specific details on how to update to new python releases, so someone might step up.
