### ISSUE TITLE
Wrapper Function Does Not Work in Python 3.12

### ISSUE THREAD

**Issue by sanssecours** [zephyrproject-rtos/windows-curses#48]
# Description

It looks like using the function `wrapper` fails, if we use Python 3.12 (to execute the code below). 

# Steps to Reproduce

1. Store the following code:

   ```py
   from curses import wrapper
   from time import sleep


   def user_interface(stdscr):
       stdscr.addstr("Hello")
       stdscr.refresh()
       while True:
           sleep(0.1)
           pass


   def main():
       wrapper(user_interface)


   if __name__ == "__main__":
       main()
   ```

   in a file called `example.py`

2. Execute the file in a terminal window:

   ```sh
   python example.py
   ```

# Expected Result

The terminal window should something like this:

![Wrapper](https://github.com/zephyrproject-rtos/windows-curses/assets/691989/b2f23759-1a58-4ae8-9f8b-61b936801a13)

# Actual Result

The script exits with an error (`$?` is set to `False`):

![Failed](https://github.com/zephyrproject-rtos/windows-curses/assets/691989/90db221b-4026-47d1-b342-2764a207231a)

# System Information

- Python: Python `3.12`
- OS: Windows `10`
- Windows Curses: Version `2.3.2`

**Comment by stephanosio** [comment]
[v2.3.3](https://github.com/zephyrproject-rtos/windows-curses/releases/tag/v2.3.3), which fixes this issue, has been released.
