### ISSUE TITLE
Could you make a tutorial?

### ISSUE THREAD

**Issue by hirios** [zephyrproject-rtos/windows-curses#5]
I don't know the English very well, so I just didn't understand how to use the project? Could you try to explain some ways or make a video tutorial?

**Comment by ulfalizer** [comment]
Hello,

This project makes [the standard Python `curses` library](https://docs.python.org/3/library/curses.html) work on Microsoft Windows. Normally, that library only works on Linux and MacOS and some other systems, and does not work on Windows.

To use this project, run this command in `cmd.exe`:

    $ pip install windows-curses

After running that command, the standard Python `curses` library will work.

To find tutorials, search for something like "python curses tutorial". Maybe there are tutorials in Portuguese too.

Good luck!

**Comment by hirios** [comment]
> Olá,
> 
> Este projeto faz [a `curses`biblioteca Python padrão](https://docs.python.org/3/library/curses.html) funcionar no Microsoft Windows. Normalmente, essa biblioteca funciona apenas no Linux e MacOS e em alguns outros sistemas operacionais e não funciona no Windows.
> 
> Para usar este projeto, execute este comando em `cmd.exe`:
> 
> ```
> pip install windows-curses
> ```
> 
> Depois de executar esse comando, a `curses`biblioteca Python padrão funcionará.
> 
> Para encontrar tutoriais, procure algo como "tutorial sobre maldições em python". Talvez também haja tutoriais em português.
> 
> Boa sorte!

Thank you very much, as soon as I have time I will test and be back to close the end of the topic

**Comment by hirios** [comment]
It worked great!! Thank you so much for this!
