### ISSUE TITLE
For ì and ^ key presses (italian keyboard), getch() always returns 0

### ISSUE THREAD

**Issue by tomatoma78** [zephyrproject-rtos/windows-curses#51]
windows-curses 2.3.2
Python 3.11.0

keypad(True) (otherwise getch() does not detect that key is pressed)

When pressing ì or ^ (key between ' or ? key and BS key) getch() returns 0

Similar to the issue affecting ] or }

**Comment by stephanosio** [comment]
This issue might have been fixed by v2.4.0. Please comment if this issue persists.
