### ISSUE TITLE
Please delete dysfunctional Python 3.12 windows-curses build from PyPI

### ISSUE THREAD

**Issue by daver1691** [zephyrproject-rtos/windows-curses#52]
If there's nobody to maintain this package, then so be it, but can somebody please delete the dysfunctional Python 3.12 windows-curses wheel from PyPI, and remove the info on its PyPI web page saying it's compatible with Python 3.12.

It's a whole lot better for people to be supplied nothing when they try to install windows-curses, than be supplied something that silently exits when they try to use it. I've seen people on the beginner's subreddit "learnpython" saying that windows-curses "does nothing" and "does not work". If they knew that they had to downgrade to Python 3.11 to use it, that would be something.

**Comment by kaecy** [comment]
Pretty sure that's a python problem not a project issue. Lots of projects have stopped working with python 3.12 including wxpython.

**Comment by Ddhruv-IOT** [comment]
> Pretty sure that's a python problem not a project issue. Lots of projects have stopped working with python 3.12 including wxpython.



> If there's nobody to maintain this package, then so be it, but can somebody please delete the dysfunctional Python 3.12 windows-curses wheel from PyPI, and remove the info on its PyPI web page saying it's compatible with Python 3.12.
> 
> It's a whole lot better for people to be supplied nothing when they try to install windows-curses, than be supplied something that silently exits when they try to use it. I've seen people on the beginner's subreddit "learnpython" saying that windows-curses "does nothing" and "does not work". If they knew that they had to downgrade to Python 3.11 to use it, that would be something.

Thanks for this, it worked, I was on py12, then I downgrade to Py11.
