### ISSUE TITLE
Fix for keyboard weirdness

### ISSUE THREAD

**Issue by gotyaoi** [zephyrproject-rtos/windows-curses#59]
Relating to #41 and #51, after doing some troubleshooting on my end, this can be solved by updating PDCurses to the 3.9 tag, sha: 6c1f95c4fa9f9f105879c2d99dd72a5bf335c046. As the gitmodules in this repo points to a fork, that for will need to be updated (or we can point to the main wmcbrine repo).

Tested on windows 11 10.0.22631, python 3.12.3.

**Comment by gotyaoi** [comment]
Had some time, so did a little bisecting.

commit 6c1f95c4fa9f9f105879c2d99dd72a5bf335c046 on sep 4 2019 is ok. (the 3.9 tag)
commit ffb83fab0f7dcabdc40176e2e87fbff46e983d01 on july 7 2021 is ok (last commit before it goes bad)
commit 07e4d2d8c82ef3af72665d783bfe05b198d47883 on july 10 2021 is not ok (introduced the problem)
commit 2e15c90f122fef329b83a4c3c011f192d97ec516 on oct 19 2021 is not ok (where windows-curses is)
commit 6c31f226922bd8653e7ed40cd4b11cee9845ea97 on nov 19 2021 is ok (reverted the problem commit)
commit 5c62af03e9a05e3a3ae8c8354c1234b772dcf4b0 on jul 12 2023 is ok (HEAD of master branch)

So windows curses could go back to 3.9, could go to immediately before or after the problem, or could go to HEAD. I could put in a PR for any of those @stephanosio?

**Comment by gotyaoi** [comment]
@stephanosio ping?

**Comment by stephanosio** [comment]
@gotyaoi I apologise for the late reply. I will look into updating PDCurses to the latest master (5c62af03e9a05e3a3ae8c8354c1234b772dcf4b0).

**Comment by stephanosio** [comment]
[windows-curses 2.4.0a2](https://github.com/zephyrproject-rtos/windows-curses/releases/tag/v2.4.0a2) has been released with the updated PDCurses.

@gotyaoi Please let me know if this fixes the issue.

**Comment by gotyaoi** [comment]
@stephanosio 2.4.0a5 produces proper results for apostrophe and close square bracket for me. I cannot test for the italian keyboard situation in #51 though.

**Comment by stephanosio** [comment]
Fixed by v2.4.0. Please comment if this issue persists.
