### ISSUE TITLE
cannot move cursor immediately

### ISSUE THREAD

**Issue by thautwarm** [zephyrproject-rtos/windows-curses#7]
This code works totally different with windows-cursers and cursers bundled in Python stdlib.

```python
def main():
    window = curses.initscr()
    curses.noecho()
    curses.nonl()
    curses.nocbreak()
    curses.raw()
    window.keypad(False)
    x = 0
    y = 0
    while True:
        window.refresh()
        c = window.getch()
        window.addstr(0, 0, str(c))
        if c == KEYS.q:
            return
        elif c == KEYS.a:
            x = 10
        elif c == KEYS.b:
            y = 10
        else:
            x = 0
            y = 0
            pass

        window.move(y, x)

        print(window.getyx())


try:
    main()
finally:
    curses.endwin()
```

Under Linux distros everything works perfectly, but for windows-cursers, the cursor can only change after the next input.

**Comment by ulfalizer** [comment]
I can't reproduce this. When I press `a`, the cursor immediately jumps to (0, 10), and then to (10, 10) when I press `b` (and back to (0, 0) when I press any other key). The cursor position is printed correctly too.

I used this slightly modified test program that avoids mixing `curses` and `print` output, but I didn't see any issues with the original version either (`getch()` implicitly does a refresh):

```python
import curses


def main():
    window = curses.initscr()
    curses.noecho()
    curses.nonl()
    curses.nocbreak()
    curses.raw()
    window.keypad(False)
    x = 0
    y = 0
    while True:
        c = window.getch()
        if c == ord('q'):
            return
        elif c == ord('a'):
            x = 10
        elif c == ord('b'):
            y = 10
        else:
            x = 0
            y = 0

        window.erase()
        window.move(y, x)
        window.addstr(0, 0, str(window.getyx()))
        window.move(y, x)


try:
    main()
finally:
    curses.endwin()
```

Are you using the standard `cmd.exe`? Anything else you can think of that might be unusual with your setup?

**Comment by thautwarm** [comment]
@ulfalizer Oh, thanks, you're right. I tried in PowerShell and cmd, both works perfectly.
The issue gets raised when using PowerShell and cmd hosted by Windows Terminal.

**Comment by ulfalizer** [comment]
Thanks for opening an upstream bug for it!
